version: "3"

services:
  auth-service:
    container_name: subql_network_auth_service
    image: onfinality/subql-network-auth-service:v0.0.1
    ports:
      - 3030:3030
    environment:
      - SK=""
      - CONSUMER=""
      - CHAIN_ID=1287